// Loosely translated from: https://docs.emmet.io/cheat-sheet/
const emmet = {
  pos: 'position',
  t: 'top',
  r: 'right',
  b: 'bottom',
  l: 'left',
  z: 'z-index',
  fl: 'float',
  cl: 'clear',
  d: 'display',
  v: 'visibility',
  ov: 'overflow',
  ovx: 'overflow-x',
  ovy: 'overflow-y',
  zm: 'zoom',
  cp: 'clip',
  rsz: 'resize',
  cur: 'cursor',

  m: 'margin',
  mt: 'margin-top',
  mr: 'margin-right',
  mb: 'margin-bottom',
  ml: 'margin-left',
  p: 'padding',
  pt: 'padding-top',
  pr: 'padding-right',
  pb: 'padding-bottom',
  pl: 'padding-left',

  bxz: 'box-sizing',
  bxsh: 'box-shadow',
  w: 'width',
  h: 'height',
  maw: 'max-width',
  mah: 'max-height',
  miw: 'min-width',
  mih: 'min-height',

  f: 'font',
  fw: 'font-weight',
  fs: 'font-style',
  fv: 'font-variant',
  fz: 'font-size',
  ff: 'font-family',

  va: 'vertical-align',
  ta: 'text-align',
  td: 'text-decoration',
  ti: 'text-indent',
  tt: 'text-transform',
  tsh: 'text-shadow',
  lh: 'line-height',
  lts: 'letter-spacing',
  whs: 'white-space',
  wob: 'word-break',
  wow: 'word-wrap',

  bg: 'background',
  bgc: 'background-color',
  bgi: 'background-image',
  bgr: 'background-repeat',
  bgo: 'background-origin',
  bgsz: 'background-size',

  c: 'color',
  o: 'opacity',
  ol: 'outline',

  br: 'border-radius',
  bd: 'border',
  bdr: 'border-right',
  bdb: 'border-bottom',
  bdl: 'border-left',
  bdt: 'border-top',
  bdc: 'border-color',

  fx: 'flex',
  fxb: 'flex-basis',
  fxd: 'flex-direction',
  fxf: 'flex-flow',
  fxg: 'flex-grow',
  fxsh: 'flex-shrink',
  fxw: 'flex-wrap',
  jc: 'justify-content',
  ji: 'justify-items',
  js: 'justify-selv',
  ac: 'align-content',
  ai: 'align-items',
  as: 'align-self',
  pc: 'place-content',
  pi: 'place-items',
  ps: 'place-self',
  mar: 'max-resolution',
  mir: 'min-resolution',
  trs: 'transition',

  g: 'grid',
  gt: 'grid-template',
  gtr: 'grid-template-rows',
  gtc: 'grid-template-columns',
  gta: 'grid-template-areas',
  ga: 'grid-area',
  gg: 'grid-gap',
  gcg: 'grid-column-gap',
  grg: 'grid-row-gap',

  gac: 'grid-auto-columns',
  gar: 'grid-auto-rows',
  gaf: 'grid-auto-flow',

  gc: 'grid-column',
  gcs: 'grid-column-start',
  gce: 'grid-column-end',

  gr: 'grid-row',
  grs: 'grid-row-start',
  gre: 'grid-row-end'
}

module.exports = (p, v) => emmet[p] != null ? [[emmet[p], v]] : null
